/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiGenerateLayoutRouteImport } from './routes/_authenticated/ai-generate-layout'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedReviewIndexRouteImport } from './routes/_authenticated/review/index'
import { Route as AuthenticatedEditionsIndexRouteImport } from './routes/_authenticated/editions/index'
import { Route as AuthenticatedReviewIdRouteImport } from './routes/_authenticated/review/$id'
import { Route as AuthenticatedPublishedIdRouteImport } from './routes/_authenticated/published/$id'
import { Route as AuthenticatedEditionsIdRouteImport } from './routes/_authenticated/editions/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiGenerateLayoutRoute =
  AuthenticatedAiGenerateLayoutRouteImport.update({
    id: '/ai-generate-layout',
    path: '/ai-generate-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewIndexRoute =
  AuthenticatedReviewIndexRouteImport.update({
    id: '/review/',
    path: '/review/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditionsIndexRoute =
  AuthenticatedEditionsIndexRouteImport.update({
    id: '/editions/',
    path: '/editions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewIdRoute = AuthenticatedReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishedIdRoute =
  AuthenticatedPublishedIdRouteImport.update({
    id: '/published/$id',
    path: '/published/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditionsIdRoute = AuthenticatedEditionsIdRouteImport.update({
  id: '/editions/$id',
  path: '/editions/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/ai-generate-layout': typeof AuthenticatedAiGenerateLayoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/editions/$id': typeof AuthenticatedEditionsIdRoute
  '/published/$id': typeof AuthenticatedPublishedIdRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/editions/': typeof AuthenticatedEditionsIndexRoute
  '/review/': typeof AuthenticatedReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/ai-generate-layout': typeof AuthenticatedAiGenerateLayoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/editions/$id': typeof AuthenticatedEditionsIdRoute
  '/published/$id': typeof AuthenticatedPublishedIdRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/editions': typeof AuthenticatedEditionsIndexRoute
  '/review': typeof AuthenticatedReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/ai-generate-layout': typeof AuthenticatedAiGenerateLayoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/editions/$id': typeof AuthenticatedEditionsIdRoute
  '/_authenticated/published/$id': typeof AuthenticatedPublishedIdRoute
  '/_authenticated/review/$id': typeof AuthenticatedReviewIdRoute
  '/_authenticated/editions/': typeof AuthenticatedEditionsIndexRoute
  '/_authenticated/review/': typeof AuthenticatedReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/ai-generate-layout'
    | '/dashboard'
    | '/pipeline'
    | '/editions/$id'
    | '/published/$id'
    | '/review/$id'
    | '/editions/'
    | '/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/ai-generate-layout'
    | '/dashboard'
    | '/pipeline'
    | '/editions/$id'
    | '/published/$id'
    | '/review/$id'
    | '/editions'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/about'
    | '/_authenticated/ai-generate-layout'
    | '/_authenticated/dashboard'
    | '/_authenticated/pipeline'
    | '/_authenticated/editions/$id'
    | '/_authenticated/published/$id'
    | '/_authenticated/review/$id'
    | '/_authenticated/editions/'
    | '/_authenticated/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-generate-layout': {
      id: '/_authenticated/ai-generate-layout'
      path: '/ai-generate-layout'
      fullPath: '/ai-generate-layout'
      preLoaderRoute: typeof AuthenticatedAiGenerateLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/': {
      id: '/_authenticated/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof AuthenticatedReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editions/': {
      id: '/_authenticated/editions/'
      path: '/editions'
      fullPath: '/editions/'
      preLoaderRoute: typeof AuthenticatedEditionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$id': {
      id: '/_authenticated/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof AuthenticatedReviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published/$id': {
      id: '/_authenticated/published/$id'
      path: '/published/$id'
      fullPath: '/published/$id'
      preLoaderRoute: typeof AuthenticatedPublishedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editions/$id': {
      id: '/_authenticated/editions/$id'
      path: '/editions/$id'
      fullPath: '/editions/$id'
      preLoaderRoute: typeof AuthenticatedEditionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAiGenerateLayoutRoute: typeof AuthenticatedAiGenerateLayoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedEditionsIdRoute: typeof AuthenticatedEditionsIdRoute
  AuthenticatedPublishedIdRoute: typeof AuthenticatedPublishedIdRoute
  AuthenticatedReviewIdRoute: typeof AuthenticatedReviewIdRoute
  AuthenticatedEditionsIndexRoute: typeof AuthenticatedEditionsIndexRoute
  AuthenticatedReviewIndexRoute: typeof AuthenticatedReviewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAiGenerateLayoutRoute: AuthenticatedAiGenerateLayoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedEditionsIdRoute: AuthenticatedEditionsIdRoute,
  AuthenticatedPublishedIdRoute: AuthenticatedPublishedIdRoute,
  AuthenticatedReviewIdRoute: AuthenticatedReviewIdRoute,
  AuthenticatedEditionsIndexRoute: AuthenticatedEditionsIndexRoute,
  AuthenticatedReviewIndexRoute: AuthenticatedReviewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
