/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrganizationSettingsRouteImport } from './routes/_authenticated/organization-settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMultiplatformRouteImport } from './routes/_authenticated/multiplatform'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiGenerateLayoutRouteImport } from './routes/_authenticated/ai-generate-layout'
import { Route as AuthenticatedAccessDeniedRouteImport } from './routes/_authenticated/access-denied'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedReviewIndexRouteImport } from './routes/_authenticated/review/index'
import { Route as AuthenticatedEditionsIndexRouteImport } from './routes/_authenticated/editions/index'
import { Route as AuthenticatedReviewIdRouteImport } from './routes/_authenticated/review/$id'
import { Route as AuthenticatedPublishedIdRouteImport } from './routes/_authenticated/published/$id'
import { Route as AuthenticatedMultiplatformInstagramRouteImport } from './routes/_authenticated/multiplatform_.instagram'
import { Route as AuthenticatedEditionsIdRouteImport } from './routes/_authenticated/editions/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationSettingsRoute =
  AuthenticatedOrganizationSettingsRouteImport.update({
    id: '/organization-settings',
    path: '/organization-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMultiplatformRoute =
  AuthenticatedMultiplatformRouteImport.update({
    id: '/multiplatform',
    path: '/multiplatform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiGenerateLayoutRoute =
  AuthenticatedAiGenerateLayoutRouteImport.update({
    id: '/ai-generate-layout',
    path: '/ai-generate-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessDeniedRoute =
  AuthenticatedAccessDeniedRouteImport.update({
    id: '/access-denied',
    path: '/access-denied',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewIndexRoute =
  AuthenticatedReviewIndexRouteImport.update({
    id: '/review/',
    path: '/review/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditionsIndexRoute =
  AuthenticatedEditionsIndexRouteImport.update({
    id: '/editions/',
    path: '/editions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewIdRoute = AuthenticatedReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishedIdRoute =
  AuthenticatedPublishedIdRouteImport.update({
    id: '/published/$id',
    path: '/published/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMultiplatformInstagramRoute =
  AuthenticatedMultiplatformInstagramRouteImport.update({
    id: '/multiplatform_/instagram',
    path: '/multiplatform/instagram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditionsIdRoute = AuthenticatedEditionsIdRouteImport.update({
  id: '/editions/$id',
  path: '/editions/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/access-denied': typeof AuthenticatedAccessDeniedRoute
  '/ai-generate-layout': typeof AuthenticatedAiGenerateLayoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/multiplatform': typeof AuthenticatedMultiplatformRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/organization-settings': typeof AuthenticatedOrganizationSettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/editions/$id': typeof AuthenticatedEditionsIdRoute
  '/multiplatform/instagram': typeof AuthenticatedMultiplatformInstagramRoute
  '/published/$id': typeof AuthenticatedPublishedIdRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/editions/': typeof AuthenticatedEditionsIndexRoute
  '/review/': typeof AuthenticatedReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/about': typeof AuthenticatedAboutRoute
  '/access-denied': typeof AuthenticatedAccessDeniedRoute
  '/ai-generate-layout': typeof AuthenticatedAiGenerateLayoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/multiplatform': typeof AuthenticatedMultiplatformRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/organization-settings': typeof AuthenticatedOrganizationSettingsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/editions/$id': typeof AuthenticatedEditionsIdRoute
  '/multiplatform/instagram': typeof AuthenticatedMultiplatformInstagramRoute
  '/published/$id': typeof AuthenticatedPublishedIdRoute
  '/review/$id': typeof AuthenticatedReviewIdRoute
  '/editions': typeof AuthenticatedEditionsIndexRoute
  '/review': typeof AuthenticatedReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/access-denied': typeof AuthenticatedAccessDeniedRoute
  '/_authenticated/ai-generate-layout': typeof AuthenticatedAiGenerateLayoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/multiplatform': typeof AuthenticatedMultiplatformRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/organization-settings': typeof AuthenticatedOrganizationSettingsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/editions/$id': typeof AuthenticatedEditionsIdRoute
  '/_authenticated/multiplatform_/instagram': typeof AuthenticatedMultiplatformInstagramRoute
  '/_authenticated/published/$id': typeof AuthenticatedPublishedIdRoute
  '/_authenticated/review/$id': typeof AuthenticatedReviewIdRoute
  '/_authenticated/editions/': typeof AuthenticatedEditionsIndexRoute
  '/_authenticated/review/': typeof AuthenticatedReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/access-denied'
    | '/ai-generate-layout'
    | '/dashboard'
    | '/multiplatform'
    | '/onboarding'
    | '/organization-settings'
    | '/settings'
    | '/team'
    | '/editions/$id'
    | '/multiplatform/instagram'
    | '/published/$id'
    | '/review/$id'
    | '/editions/'
    | '/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/access-denied'
    | '/ai-generate-layout'
    | '/dashboard'
    | '/multiplatform'
    | '/onboarding'
    | '/organization-settings'
    | '/settings'
    | '/team'
    | '/editions/$id'
    | '/multiplatform/instagram'
    | '/published/$id'
    | '/review/$id'
    | '/editions'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/about'
    | '/_authenticated/access-denied'
    | '/_authenticated/ai-generate-layout'
    | '/_authenticated/dashboard'
    | '/_authenticated/multiplatform'
    | '/_authenticated/onboarding'
    | '/_authenticated/organization-settings'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/editions/$id'
    | '/_authenticated/multiplatform_/instagram'
    | '/_authenticated/published/$id'
    | '/_authenticated/review/$id'
    | '/_authenticated/editions/'
    | '/_authenticated/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization-settings': {
      id: '/_authenticated/organization-settings'
      path: '/organization-settings'
      fullPath: '/organization-settings'
      preLoaderRoute: typeof AuthenticatedOrganizationSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/multiplatform': {
      id: '/_authenticated/multiplatform'
      path: '/multiplatform'
      fullPath: '/multiplatform'
      preLoaderRoute: typeof AuthenticatedMultiplatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-generate-layout': {
      id: '/_authenticated/ai-generate-layout'
      path: '/ai-generate-layout'
      fullPath: '/ai-generate-layout'
      preLoaderRoute: typeof AuthenticatedAiGenerateLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-denied': {
      id: '/_authenticated/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AuthenticatedAccessDeniedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/': {
      id: '/_authenticated/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof AuthenticatedReviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editions/': {
      id: '/_authenticated/editions/'
      path: '/editions'
      fullPath: '/editions/'
      preLoaderRoute: typeof AuthenticatedEditionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$id': {
      id: '/_authenticated/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof AuthenticatedReviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/published/$id': {
      id: '/_authenticated/published/$id'
      path: '/published/$id'
      fullPath: '/published/$id'
      preLoaderRoute: typeof AuthenticatedPublishedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/multiplatform_/instagram': {
      id: '/_authenticated/multiplatform_/instagram'
      path: '/multiplatform/instagram'
      fullPath: '/multiplatform/instagram'
      preLoaderRoute: typeof AuthenticatedMultiplatformInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editions/$id': {
      id: '/_authenticated/editions/$id'
      path: '/editions/$id'
      fullPath: '/editions/$id'
      preLoaderRoute: typeof AuthenticatedEditionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAccessDeniedRoute: typeof AuthenticatedAccessDeniedRoute
  AuthenticatedAiGenerateLayoutRoute: typeof AuthenticatedAiGenerateLayoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMultiplatformRoute: typeof AuthenticatedMultiplatformRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrganizationSettingsRoute: typeof AuthenticatedOrganizationSettingsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedEditionsIdRoute: typeof AuthenticatedEditionsIdRoute
  AuthenticatedMultiplatformInstagramRoute: typeof AuthenticatedMultiplatformInstagramRoute
  AuthenticatedPublishedIdRoute: typeof AuthenticatedPublishedIdRoute
  AuthenticatedReviewIdRoute: typeof AuthenticatedReviewIdRoute
  AuthenticatedEditionsIndexRoute: typeof AuthenticatedEditionsIndexRoute
  AuthenticatedReviewIndexRoute: typeof AuthenticatedReviewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAccessDeniedRoute: AuthenticatedAccessDeniedRoute,
  AuthenticatedAiGenerateLayoutRoute: AuthenticatedAiGenerateLayoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMultiplatformRoute: AuthenticatedMultiplatformRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrganizationSettingsRoute:
    AuthenticatedOrganizationSettingsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedEditionsIdRoute: AuthenticatedEditionsIdRoute,
  AuthenticatedMultiplatformInstagramRoute:
    AuthenticatedMultiplatformInstagramRoute,
  AuthenticatedPublishedIdRoute: AuthenticatedPublishedIdRoute,
  AuthenticatedReviewIdRoute: AuthenticatedReviewIdRoute,
  AuthenticatedEditionsIndexRoute: AuthenticatedEditionsIndexRoute,
  AuthenticatedReviewIndexRoute: AuthenticatedReviewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
